### ISSUE TITLE
Theme fails to install due to error parsing package.json

### ISSUE THREAD

**Issue by nihonjinrxs** [builders-club/vscode-twitch-themer#165] opened 2021-02-23 21:07 UTC
The [Rainbow Theme](https://marketplace.visualstudio.com/items?itemName=saikumarchinna.rainbow) fails to install due to an error parsing [the package.json file](https://github.com/Dreamyplayer/Rainbow-Theme/blob/master/package.json).

There was a note about line endings, which may or may not be relevant. I also noticed that there are some emojis in the package.json in the `"description"` field which may be an issue. Are we reading that file as a UTF-8 encoding?

**Comment by parithon** [comment] 2021-03-03 07:23
Hi @nihonjinrxs, 

Thanks for the issue! We are parsing the results of the `package.json` using UTF-8. The problem is the `package.json` for this theme does not adhere to strict JSON syntax. That is, the author has left a trailing comma which makes NodeJS' JSON.parse() throw an error.

I'm looking into a possible solution to _clean_ these types of syntax errors prior to parsing the text.

**Comment by parithon** [comment] 2021-03-17 04:38
@nihonjinrxs @MichaelJolley, I believe this issue has been resolved. I'll close it next week until somebody has any concerns.

**Closed** 2022-02-03 21:06 UTC
Labels: 🐛 bug, 📚 good first issue, 🏷️ claimed, :shipit: ship it
